### ISSUE TITLE
Which file to add the skip options

### ISSUE THREAD

**Issue by umair-me** [bglidwell/strapi-plugin-moesif#5]
Where do we add the skip configuration in strapi v4?
```
    skip: function (req, res) {
        console.log(req);
        return (
          res.headers && !res.headers["Content-Type"].includes("application/json")
        );
      }
```

**Comment by dgilling** [comment]
Hi @umair-me I believe that function is already the default skip function. [See here](https://github.com/bglidwell/strapi-plugin-moesif/blob/2cb405fc730a0cd8f897b08a7f91b969565dc6f2/server/config/default-config.js#L10). Are you looking to customize this plugin?

**Comment by bglidwell** [comment]
@umair-me In Strapi V4, you can add the skip function directly to the config where you enable the plugin. The file @dgilling linked shows the default configuration that is used, but you can override any of those values by defining them in the plugin config as shown below.

Enable the plugin ./config/plugins.js
``` 
module.exports = {
  'strapi-plugin-moesif': {
    enabled: true,
    config: {
      moesif: {
        //custom config passed to moesif middleware goes here
          skip: function (req, res) {
             //custom skip function here
          }
      }
    },
  },
}
```
